Console.Clear();
System.Random rndNum = new System.Random();
int num = rndNum.Next(100, 1000);
char[] numbs = rndNum.Next(100, 1000).ToString().ToCharArray();
Console.Write(numbs);
// int a = numbs[0]-48;
// int b = numbs[1]-48;
// int c = numbs[2]-48;
int z =numbs[1]-48 ;
//Console.WriteLine("Первое " + a + " Второе " + b + " Третье " + c);
Console.WriteLine( "-> "+z);